version: 0.1.0                                            

name: Test stack to Deploy Next.js site to GitHub pagessaasds111  # stack name 
description: Description of the test stack               # stack description

branding:                                                # stack branding 
 icon: 'package'
 color: 'black'

inputs:                                                  # stack inputs 
  - name: NODE_VERSION                                   # stack input name
    description: NODE_VERSION for nodejs stack           # stack input description
   
    
 

configs:
  repo-metadata:
    parameters:
      description: 'NextJS app on GH pages'
      topics:
      - nextjs
      - github-pages


init:
  uses: "stack-init.yaml"
